# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Publish to JetBrains Marketplace

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    environment: JetBrains Marketplace
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21 # This jdk is just for running Gradle, the compiler will be downloaded according to Gradle's build script.
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'corretto'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew buildPlugin

      - name: Run Plugin Verifier
        run: ./gradlew verifyPlugin
      # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
      # the publishing section of your build.gradle
      - name: Publish to JetBrains Marketplace
        run: ./gradlew publishPlugin
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          CERTIFICATE_CHAIN: ${{ secrets.CERTIFICATE_CHAIN }}
